DROP DATABASE IF EXISTS bookings;

CREATE DATABASE bookings;

CREATE TABLE bookings.Students (
    S_ID INT NOT NULL,
    S_NAME VARCHAR(256) NOT NULL,
    S_EMAIL VARCHAR(256) NOT NULL,
    PRIMARY KEY (S_ID)
);
